// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU67xH8HSVugb9uKuUd7zTmZHJR2LPa6s',
    appId: '1:855819574709:web:74f5a13d54e3f76b804dfc',
    messagingSenderId: '855819574709',
    projectId: 'recordingmanagement-up',
    authDomain: 'recordingmanagement-up.firebaseapp.com',
    storageBucket: 'recordingmanagement-up.appspot.com',
    measurementId: 'G-6JGYYFCRPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOiH8QurMMFdW2zBh-TZZGrpXqTp50_I',
    appId: '1:855819574709:android:f9b7e5801e54bfb4804dfc',
    messagingSenderId: '855819574709',
    projectId: 'recordingmanagement-up',
    storageBucket: 'recordingmanagement-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABeRLnd0mejDoQ4YW817ud_Ui9K2wSOTk',
    appId: '1:855819574709:ios:7281575b2a9e93e5804dfc',
    messagingSenderId: '855819574709',
    projectId: 'recordingmanagement-up',
    storageBucket: 'recordingmanagement-up.appspot.com',
    iosClientId: '855819574709-u53mqi5jr6phe1cbqv6bc27g6q3hor1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.recordingmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABeRLnd0mejDoQ4YW817ud_Ui9K2wSOTk',
    appId: '1:855819574709:ios:7281575b2a9e93e5804dfc',
    messagingSenderId: '855819574709',
    projectId: 'recordingmanagement-up',
    storageBucket: 'recordingmanagement-up.appspot.com',
    iosClientId: '855819574709-u53mqi5jr6phe1cbqv6bc27g6q3hor1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.recordingmanagement',
  );
}
